java:
  releaseNameOverride: ${SERVICE_NAME}
  image: ${IMAGE_NAME}
  replicas: 2
  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}
  environment:
    SSL_VERIFICATION_ENABLED: false
    ZUUL_SSLHOSTNAMEVALIDATIONENABLED: false

